source 'https://cdn.cocoapods.org/'

# SwiftUI preview doesn't work with static linkage framework
# but static linkage will reduce app startup time, it should be used in release
use_frameworks!
# use_frameworks! :linkage => :static


def allPods
  pod 'NukeUI', :path => '../'
  pod 'NukePod', :path => '../../NukePod'
  pod 'Gifu'
  pod 'SwiftSVG'
  pod 'Alamofire'
end

target 'NukeDemo' do
  platform :ios, '13.0'
  allPods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
